name: Docker Build and Push to GHCR

# 1. Define cuándo se ejecuta el workflow
on:
  push:
    tags:
      - 'v*.*.*' # Se ejecuta cuando empujas un tag que empieza con 'v' seguido de números (ej. v1.0.0, v2.1.3)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Asegúrate de tener este permiso para GHCR

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- AÑADIR ESTE PASO ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # --- FIN DEL PASO AÑADIDO ---

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Ahora estas líneas deberían funcionar gracias al paso anterior
          cache-from: type=gha
          cache-to: type=gha,mode=max
